Add ability to merge included nested models into their parent model (merge-include)
ignitionrobotics/sdformat pull request #659
Opened 2021-08-06 21:31 UTC by azeey

# 🎉 New feature

## Summary
This adds a new attribute, `merge`, to `//include` that when set to true copies all the children elements of the nested model into the parent model without introducing a new scope. Currently, we only merge named elements such as `//link`, `//frame` , and `//joint` as well as custom elements. This means we ignore elements like `//static` and `//enable_wind`.
 
For example, given the parent model:
```xml
<?xml version="1.0" ?>
<sdf version="1.9">
  <world name="world_model">
    <model name="robot">
      <include merge="true">
        <uri>test_model</uri>
        <pose>100 0 0 0 0 0</pose>
      </include>
    </model>
  </world>
</sdf>
```
and the included model:
```xml
<sdf version="1.9">
  <model name="test_model">
    <link name="L1" />
    <frame name="F1" />
  </model>
</sdf>
```

The result would be:
```xml
<sdf version='1.9'>
  <world name='world_model'>
    <model name='robot'>
      <frame name='__test_model__model__' attached_to='L1'>
        <pose relative_to='__model__'>100 0 0 0 -0 0</pose>
      </frame>
      <link name='L1'>
        <pose relative_to='__test_model__model__'>0 0 0 0 -0 0</pose>
      </link>
      <frame name='F1' attached_to='__test_model__model__'/>
    </model>
  </world>
```

## Test it
Set `SDF_PATH` to the absolute path of `test/integration/model` and run `ign sdf -p test/integration/merge_include_model.sdf`

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-08-07 00:04 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @azeey)

___
*[src/parser.cc, line 1584 at r1](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MgSu_0m1kW7SVJooxpA:-MgSu_0m1kW7SVJooxpB:b-zhl3r) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/1d09b0148a0fcd6caa68a9a1de6b3181fba9c2c6/src/parser.cc#L1584)):*
> ```cpp
>             includeSDFFirstElem->SetIncludeElement(includeInfo);
>           }
>           bool toMerge = _sdf->GetName() == "model" &&
> ```

It's not clear to me that this imposes the encapsulation checks.

My preference is that we uphold the invariant that a model should always be valid as a standalone component, and we should actively fail on models that are not fully standalone.

More concretely, a models should always be includable via `@merge={false,true}`, with the only differences:
- `@merge=false`: Names could now collide; should check.
- `@merge=true`: Names will be nested (only model name could collide w/ existing elements).

Is this upheld by the current code?
If not, is there a (possibly elegant / minimal) solution to uphold encapsulation?


<!-- Sent from Reviewable.io -->

2021-08-07 00:06 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @azeey)

___
*[src/parser.cc, line 1584 at r1](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MgSu_0m1kW7SVJooxpA:-MgSvTWd-Nru8HLL8R5q:byoxsg) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/1d09b0148a0fcd6caa68a9a1de6b3181fba9c2c6/src/parser.cc#L1584)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's not clear to me that this imposes the encapsulation checks.

My preference is that we uphold the invariant that a model should always be valid as a standalone component, and we should actively fail on models that are not fully standalone.

More concretely, a models should always be includable via `@merge={false,true}`, with the only differences:
- `@merge=false`: Names could now collide; should check.
- `@merge=true`: Names will be nested (only model name could collide w/ existing elements).

Is this upheld by the current code?
If not, is there a (possibly elegant / minimal) solution to uphold encapsulation?
</blockquote></details>

More specifically, an included model should not depend on frames, links, joints, etc. that are in the including context.


<!-- Sent from Reviewable.io -->

2021-08-07 10:01 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[src/parser.cc, line 1584 at r1](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MgSu_0m1kW7SVJooxpA:-MgV0Z-y5bEG6Td0VzD9:blpsf7x) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/1d09b0148a0fcd6caa68a9a1de6b3181fba9c2c6/src/parser.cc#L1584)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

More specifically, an included model should not depend on frames, links, joints, etc. that are in the including context.
</blockquote></details>

you can construct a throwaway `sdf::Model` to call the validation functions on a model to be merge-included, but that may be a bit much. Otherwise, the only functions `parser.hh` that take an `sdf::ElementPtr` as an input are for checking name uniqueness and for not misusing `::`

https://github.com/ignitionrobotics/sdformat/blob/6251baaddea3e3216c09fadb38cc6747b83bf1bf/include/sdf/parser.hh#L409-L428


<!-- Sent from Reviewable.io -->

2021-08-09 17:42 UTC, azeey commented
___
*[src/parser.cc, line 1584 at r1](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MgSu_0m1kW7SVJooxpA:-Mgfz9EjDrt4Kt4cWxoc:bb5cixu) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/1d09b0148a0fcd6caa68a9a1de6b3181fba9c2c6/src/parser.cc#L1584)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

you can construct a throwaway `sdf::Model` to call the validation functions on a model to be merge-included, but that may be a bit much. Otherwise, the only functions `parser.hh` that take an `sdf::ElementPtr` as an input are for checking name uniqueness and for not misusing `::`

https://github.com/ignitionrobotics/sdformat/blob/6251baaddea3e3216c09fadb38cc6747b83bf1bf/include/sdf/parser.hh#L409-L428
</blockquote></details>

Yeah, since the merging is done in an earlier stage of parsing, I don't think there's an elegant/minimal solution to do the full validation of a model. A less elegant way would be add a `__merge__` attribute to the model and add it as a nested model into the parent `sdf::ElementPtr` and later when `sdf::Model` is loaded, we perform the actual merge. 


<!-- Sent from Reviewable.io -->

2021-08-19 03:59 UTC, ddengster commented
Great work @azeey!

I'm looking to override/merge the `<cast_shadow>` tags of the parent model, do you think we can build on this include-merge feature to do it?

Related issues:
https://github.com/ignitionrobotics/sdformat/issues/600
https://github.com/ignitionrobotics/sdformat/issues/128

2021-08-23 15:06 UTC, azeey commented
> I'm looking to override/merge the <cast_shadow> tags of the parent model, do you think we can build on this include-merge feature to do it?

I think that would be out of scope for this PR, but I think the [parameter passing feature](http://sdformat.org/tutorials?tut=param_passing_tutorial&cat=specification&) would work for overriding `<cast_shadow>`. Have you had a chance to try that?

2021-08-23 15:10 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @azeey)

___
*[src/parser.cc, line 1584 at r1](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MgSu_0m1kW7SVJooxpA:-MhnYO821gapsIOb3uHt:b-xnztsu) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/1d09b0148a0fcd6caa68a9a1de6b3181fba9c2c6/src/parser.cc#L1584)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Yeah, since the merging is done in an earlier stage of parsing, I don't think there's an elegant/minimal solution to do the full validation of a model. A less elegant way would be add a `__merge__` attribute to the model and add it as a nested model into the parent `sdf::ElementPtr` and later when `sdf::Model` is loaded, we perform the actual merge. 
</blockquote></details>

Working: I'll see if using a throwaway `sdf::Model` would be feasible without becoming a maintenance burden.


<!-- Sent from Reviewable.io -->

2021-08-25 07:39 UTC, ddengster commented
> > I'm looking to override/merge the <cast_shadow> tags of the parent model, do you think we can build on this include-merge feature to do it?
> 
> I think that would be out of scope for this PR, but I think the [parameter passing feature](http://sdformat.org/tutorials?tut=param_passing_tutorial&cat=specification&) would work for overriding `<cast_shadow>`. Have you had a chance to try that?

will try that out, thanks!

2021-08-31 22:05 UTC, azeey commented
___
*[src/parser.cc, line 1584 at r1](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MgSu_0m1kW7SVJooxpA:-MiTE_Sy4zwQzvT3t_ka:bq91dtt) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/1d09b0148a0fcd6caa68a9a1de6b3181fba9c2c6/src/parser.cc#L1584)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Working: I'll see if using a throwaway `sdf::Model` would be feasible without becoming a maintenance burden.
</blockquote></details>

Done. Using a throwaway `sdf::Model` works pretty well. It actually makes it possible to support placement frames when `merge=true`.


<!-- Sent from Reviewable.io -->

2021-08-31 22:11 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @azeey and @EricCousineau-TRI)

___
*[src/parser.cc, line 237 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiTFPwlBm64MtvDWERh:-MiTFPwlBm64MtvDWERi:bcgjgh8) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L237)):*
> ```cpp
> 
>     ElementPtr proxyModelFrame = _parent->AddElement("frame");
>     const std::string proxyModelFrameName = model->Name() + "__model__";
> ```

FYI I changed this from `__<model name>__model__` to `<model name>__model__` because when using the former and generating an SDFormat output file, we end up having a frame with an invalid name since names that start and end with `__` are reserved by SDFormat.


<!-- Sent from Reviewable.io -->

2021-09-02 05:46 UTC, scpeters reviewed
> Reviewed 2 of 5 files at r1, 5 of 8 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 8 of 11 files reviewed, 8 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @jennuine)

___
*[src/parser.cc, line 210 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZuQWj4pJv5JnIJ_Ah:-MiZuQWj4pJv5JnIJ_Ai:b-4tqgh0) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L210)):*
> ```cpp
>       Error unsupportedError(
>           ErrorCode::MERGE_INCLUDE_UNSUPPORTED,
>           "Merge-include can not supported when parent element is " +
> ```

nit: rephrase to "Merge-include does not support parent elements of type " + `_parent->GetName()`
___
*[src/parser.cc, line 237 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZy92J5D3fx06jt-S-:-MiZy92J5D3fx06jt-S0:bmig52s) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L237)):*
> ```cpp
> 
>     ElementPtr proxyModelFrame = _parent->AddElement("frame");
>     const std::string proxyModelFrameName = model->Name() + "__model__";
> ```

it's an edge case, but I think this frame name could be invalid if the model name starts with `__`:

~~~
<model name="__valid_model_name">
...
</model>
~~~

would give a frame name of `__valid_model_name__model__`
___
*[src/parser.cc, line 333 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-Mi_1Tqh36PsejXr6ATC:-Mi_1Tqh36PsejXr6ATD:b-kbpf7z) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L333)):*
> ```cpp
>       if ((elem->GetName() == "link") || (elem->GetName() == "model") ||
>           (elem->GetName() == "joint") || (elem->GetName() == "frame") ||
>           (elem->GetName() == "plugin") ||
> ```

consider adding "gripper" as well, as I just noticed that it is a named element as well

https://github.com/ignitionrobotics/sdformat/blob/sdformat11_11.2.2/sdf/1.8/model.sdf#L38
https://github.com/ignitionrobotics/sdformat/blob/sdformat11_11.2.2/sdf/1.8/gripper.sdf#L5
___
*[src/parser.cc, line 353 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZu_yf8Z8a1GFkSnc9:-MiZu_yf8Z8a1GFkSncA:babplod) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L353)):*
> ```cpp
>     firstElem->SetParent(_parent);
>     _parent->InsertElement(firstElem);
>   }
> ```

nit: I feel like this function would be a bit more readable if these short `else if` and `else` logic blocks came first. Currently I have to scroll past all the merge logic just to see the different branches. Perhaps it could start with:

~~~
if (!_merge)
{
  firstElem->SetParent(_parent);
  _parent->InsertElement(firstElem);
  return;
}
else if (firstElem->GetName() == "model")
{
  Error unsupportedError(
      ErrorCode::MERGE_INCLUDE_UNSUPPORTED,
      "Merge-include is only supported for included models");
  _sourceLoc.SetSourceLocationOnError(unsupportedError);
  _errors.push_back(unsupportedError);
  return;
}
~~~

then the code from the original `if (_merge && firstElem->GetName() == "model")` branch can be placed here, with or without a containing `else` block, since the other branches `return;`

actually the other error branch can be appended as well as `else if (_parent->GetName() != "model")`
___
*[test/integration/includes.cc, line 496 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZu8x_2qafC3_oLfug:-MiZu8x_2qafC3_oLfuh:b20vzsl) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/includes.cc#L496)):*
> ```cpp
> {
>   sdf::ParserConfig config;
>   // Useing the "file://" URI scheme to allow multiple search paths
> ```

Useing -> Using
___
*[test/integration/model/merge_robot/model.sdf, line 275 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-Mi_0OtNBT9c7vI0-hb-:-Mi_0OtNBT9c7vI0-hb0:bxfqnbg) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/model/merge_robot/model.sdf#L275)):*
> ```
> 
>     <joint name='right_wheel_joint' type='revolute'>
>       <pose relative_to='__model__'>1 0 0 0 0 0</pose>
> ```

there is special logic for handling `__model__` in the attributes, but I didn't see any test expectations confirming these values

to be thorough, you could add a `//frame` with attribute values of `__model__` and a joint with `//axis/xyz/@expressed_in == "__model__"` to test that logic as well
___
*[test/sdf/model_invalid_frame_only.sdf, line 5 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZtzgh2JYSi_a1DCAd:-MiZtzgi4RP_0uCJgbLn:b-prc1rm) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/sdf/model_invalid_frame_only.sdf#L5)):*
> ```
>   <model name="model_invalid_frame_only">
>     <frame name="F1"/>
>     <frame name="F2"/> 
> ```

nit: trailing whitespace on this line


<!-- Sent from Reviewable.io -->

2021-09-02 23:02 UTC, jennuine reviewed
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 8 of 11 files reviewed, 12 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[test/integration/includes.cc, line 591 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MicfUve5uf2OPuUvUi9:-MicfUvf4x57c7C6BS9k:b-qxex7w) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/includes.cc#L591)):*
> ```
>     std::stringstream buffer;
>     sdf::testing::RedirectConsoleStream redir(
>         sdf::Console::Instance()->GetMsgStream(), &buffer);
> ```

Would adding this fix the windows CI failure?:
https://github.com/ignitionrobotics/sdformat/blob/a797e18eeb012012f02f194178b16b5bf847fe39/test/integration/deprecated_specs.cc#L77-L84
___
*[test/integration/model/merge_robot/model.config, line 4 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MicgAf81oOGLP4k5Fuy:-MicgAf81oOGLP4k5Fuz:b-n1azjt) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/model/merge_robot/model.config#L4)):*
> ```
> <model>
>   <name>robot</name>
>   <sdf version="1.7">model.sdf</sdf>
> ```

1.7 -> 1.9?
___
*[test/integration/model/merge_robot/model.sdf, line 2 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MicgG4t8rQucBNvTUTV:-MicgG4t8rQucBNvTUTW:bi3p1mw) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/model/merge_robot/model.sdf#L2)):*
> ```
> <?xml version='1.0' ?>
> <sdf version='1.8' xmlns:custom="http://example.org/schema">
> ```

1.8 -> 1.9?
___
*[test/sdf/model_invalid_frame_only.sdf, line 2 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MicimG83Acm3CKRNfLc:-MicimG83Acm3CKRNfLd:b-n1azjt) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/sdf/model_invalid_frame_only.sdf#L2)):*
> ```
> <?xml version="1.0" ?>
> <sdf version='1.7'>
> ```

1.7 -> 1.9?


<!-- Sent from Reviewable.io -->

2021-09-08 21:49 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 4 of 11 files reviewed, 9 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, @jennuine, and @scpeters)

___
*[src/parser.cc, line 210 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZuQWj4pJv5JnIJ_Ah:-Mj6LhRj7LgzLJeEpEei:b-103upk) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L210)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: rephrase to "Merge-include does not support parent elements of type " + `_parent->GetName()`
</blockquote></details>

Done in https://github.com/ignitionrobotics/sdformat/pull/659/commits/923cc729451f4aa98b801ac7fec54323d726d5b6
___
*[src/parser.cc, line 237 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZy92J5D3fx06jt-S-:-Mj6MsG2E0XHRLb0rmEK:bynvx1f) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L237)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

it's an edge case, but I think this frame name could be invalid if the model name starts with `__`:

~~~
<model name="__valid_model_name">
...
</model>
~~~

would give a frame name of `__valid_model_name__model__`
</blockquote></details>

That's a good point. I'm not sure how we can avoid that unless we also reserve all names that start with double underscore. Alternatively, we can modify the poses of each element and not use a frame. 
___
*[src/parser.cc, line 333 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-Mi_1Tqh36PsejXr6ATC:-Mj6LlAY3fEmbvqffdtP:b-jjqem9) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L333)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

consider adding "gripper" as well, as I just noticed that it is a named element as well

https://github.com/ignitionrobotics/sdformat/blob/sdformat11_11.2.2/sdf/1.8/model.sdf#L38
https://github.com/ignitionrobotics/sdformat/blob/sdformat11_11.2.2/sdf/1.8/gripper.sdf#L5
</blockquote></details>

Done. https://github.com/ignitionrobotics/sdformat/pull/659/commits/923cc729451f4aa98b801ac7fec54323d726d5b6
___
*[src/parser.cc, line 353 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZu_yf8Z8a1GFkSnc9:-Mj6LoEc9GQdb4haHEpo:b-t1si90) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L353)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: I feel like this function would be a bit more readable if these short `else if` and `else` logic blocks came first. Currently I have to scroll past all the merge logic just to see the different branches. Perhaps it could start with:

~~~
if (!_merge)
{
  firstElem->SetParent(_parent);
  _parent->InsertElement(firstElem);
  return;
}
else if (firstElem->GetName() == "model")
{
  Error unsupportedError(
      ErrorCode::MERGE_INCLUDE_UNSUPPORTED,
      "Merge-include is only supported for included models");
  _sourceLoc.SetSourceLocationOnError(unsupportedError);
  _errors.push_back(unsupportedError);
  return;
}
~~~

then the code from the original `if (_merge && firstElem->GetName() == "model")` branch can be placed here, with or without a containing `else` block, since the other branches `return;`

actually the other error branch can be appended as well as `else if (_parent->GetName() != "model")`
</blockquote></details>

Done. I agree it's a bit more readable. https://github.com/ignitionrobotics/sdformat/pull/659/commits/923cc729451f4aa98b801ac7fec54323d726d5b6
___
*[test/integration/includes.cc, line 496 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZu8x_2qafC3_oLfug:-Mj6LrhH4jf90jV6tsHO:b-jjqem9) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/includes.cc#L496)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

Useing -> Using
</blockquote></details>

Done. https://github.com/ignitionrobotics/sdformat/pull/659/commits/923cc729451f4aa98b801ac7fec54323d726d5b6
___
*[test/integration/includes.cc, line 591 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MicfUve5uf2OPuUvUi9:-Mj6LtkQ2RZeEBGs8PBa:bv0sw4q) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/includes.cc#L591)):*
<details><summary><i>Previously, jennuine (Jenn Nguyen) wrote…</i></summary><blockquote>

> ```
>     std::stringstream buffer;
>     sdf::testing::RedirectConsoleStream redir(
>         sdf::Console::Instance()->GetMsgStream(), &buffer);
> ```

Would adding this fix the windows CI failure?:
https://github.com/ignitionrobotics/sdformat/blob/a797e18eeb012012f02f194178b16b5bf847fe39/test/integration/deprecated_specs.cc#L77-L84
</blockquote></details>

Yeah, I think that's the fix. Thanks! https://github.com/ignitionrobotics/sdformat/pull/659/commits/923cc729451f4aa98b801ac7fec54323d726d5b6
___
*[test/integration/model/merge_robot/model.config, line 4 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MicgAf81oOGLP4k5Fuy:-Mj6M3eU8zB_NoDDU4xc:b-k1i3au) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/model/merge_robot/model.config#L4)):*
<details><summary><i>Previously, jennuine (Jenn Nguyen) wrote…</i></summary><blockquote>

1.7 -> 1.9?
</blockquote></details>

Per VC, I think this should remain 1.7 since it doesn't use any syntax from 1.9
___
*[test/integration/model/merge_robot/model.sdf, line 2 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MicgG4t8rQucBNvTUTV:-Mj6MLRGBkf3Ho1Ya1Jy:b-k1i3au) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/model/merge_robot/model.sdf#L2)):*
<details><summary><i>Previously, jennuine (Jenn Nguyen) wrote…</i></summary><blockquote>

1.8 -> 1.9?
</blockquote></details>

Per VC, I think this should remain 1.7 since it doesn't use any syntax from 1.9
___
*[test/integration/model/merge_robot/model.sdf, line 275 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-Mi_0OtNBT9c7vI0-hb-:-Mj6MNLN77cCnEu4nMzv:b-3w7nvg) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/model/merge_robot/model.sdf#L275)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

there is special logic for handling `__model__` in the attributes, but I didn't see any test expectations confirming these values

to be thorough, you could add a `//frame` with attribute values of `__model__` and a joint with `//axis/xyz/@expressed_in == "__model__"` to test that logic as well
</blockquote></details>

Done. Added more tests in https://github.com/ignitionrobotics/sdformat/pull/659/commits/923cc729451f4aa98b801ac7fec54323d726d5b6. Instead creating a new joint, I modified the existing one. Let me know if that's okay.
___
*[test/sdf/model_invalid_frame_only.sdf, line 2 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MicimG83Acm3CKRNfLc:-Mj6MbldAJM7uY8r3ZDO:b-k1i3au) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/sdf/model_invalid_frame_only.sdf#L2)):*
<details><summary><i>Previously, jennuine (Jenn Nguyen) wrote…</i></summary><blockquote>

1.7 -> 1.9?
</blockquote></details>

Per VC, I think this should remain 1.7 since it doesn't use any syntax from 1.9
___
*[test/sdf/model_invalid_frame_only.sdf, line 5 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZtzgh2JYSi_a1DCAd:-Mj6Ma146 [...]

2021-09-08 23:16 UTC, scpeters reviewed
> Reviewed 4 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, @jennuine, and @scpeters)

___
*[test/integration/model/merge_robot/model.sdf, line 2 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MicgG4t8rQucBNvTUTV:-Mj6gPQ2-Uvn0EsFqTTd:bt9hw94) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/model/merge_robot/model.sdf#L2)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Per VC, I think this should remain 1.7 since it doesn't use any syntax from 1.9
</blockquote></details>

it looks like `sensor_frame` is using `//pose/@degrees`, so I think it should be 1.9


<!-- Sent from Reviewable.io -->

2021-09-08 23:22 UTC, scpeters requested changes
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 8 of 11 files reviewed, 8 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, @jennuine, and @scpeters)

___
*[test/integration/includes.cc, line 671 at r5](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-Mj6hykoEUj27RR1Fh0G:-Mj6hykp9_8ixTF3ZEMd:b-nil8ki) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/923cc729451f4aa98b801ac7fec54323d726d5b6/test/integration/includes.cc#L671)):*
> ```cpp
>     EXPECT_EQ(5, *errors[0].LineNumber());
>     EXPECT_TRUE(buffer.str().find("Error parsing XML in file") !=
>                 std::string::npos);
> ```

suggest adding `<< buffer.str()` between closing `)` and `;` to aid in debugging the windows test failure


<!-- Sent from Reviewable.io -->

2021-09-09 21:08 UTC, azeey commented
*[a discussion](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MjBBFD74RzhJ3ngWVcM:-MjBBFD74RzhJ3ngWVcN:b-brsnol) (no related file):*
@ericcousineau-tri  I've confirmed that this doesn't work with interface models. My proposed fix is the following:
* Add an `isMerged` flag to `sdf::NestedInclude`. This would let the custom parser know to parse the model and merge the contents with the parent model. This would also mean Drake would have to be updated to support this.
* Add member functions `InterfaceLinks`, `InterfaceFrames`, and `InterfaceJoints` to `sdf::Model`. Currently only `sdf::InterfaceModel` has those functions. If an interface model is to be merged, we need these functions in the parent model to access the merged interface elements
* Update `FrameSemantics.cc` to to take into account Interface elements directly under `sdf::Model`.

---


<!-- Sent from Reviewable.io -->

2021-09-14 22:16 UTC, azeey commented
*[a discussion](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MjBBFD74RzhJ3ngWVcM:-MjaMp4F4HO5x4qJQY9-:bqxy3qe) (no related file):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

@ericcousineau-tri  I've confirmed that this doesn't work with interface models. My proposed fix is the following:
* Add an `isMerged` flag to `sdf::NestedInclude`. This would let the custom parser know to parse the model and merge the contents with the parent model. This would also mean Drake would have to be updated to support this.
* Add member functions `InterfaceLinks`, `InterfaceFrames`, and `InterfaceJoints` to `sdf::Model`. Currently only `sdf::InterfaceModel` has those functions. If an interface model is to be merged, we need these functions in the parent model to access the merged interface elements
* Update `FrameSemantics.cc` to to take into account Interface elements directly under `sdf::Model`.


</blockquote></details>

Okay, I started working on what I proposed, but I soon realized that it's quite complicated and would need more time to properly test. So, instead, I PIMPLized the `sdf::NestedInclude` class so that we can fix this after the Fortress release.

---


<!-- Sent from Reviewable.io -->

2021-09-14 22:29 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 7 of 18 files reviewed, 8 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, @jennuine, and @scpeters)

___
*[test/integration/includes.cc, line 671 at r5](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-Mj6hykoEUj27RR1Fh0G:-MjaMfBC1S4EcDwNgcwB:b-hyfbey) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/923cc729451f4aa98b801ac7fec54323d726d5b6/test/integration/includes.cc#L671)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

suggest adding `<< buffer.str()` between closing `)` and `;` to aid in debugging the windows test failure
</blockquote></details>

Done in https://github.com/ignitionrobotics/sdformat/pull/659/commits/e7dc8be3e1ec2b89a7d6564deeccc1129c45d0e0. 
___
*[test/integration/model/merge_robot/model.sdf, line 2 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MicgG4t8rQucBNvTUTV:-MjaMHVO1vv-22IS0K8g:b1frfjz) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/model/merge_robot/model.sdf#L2)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

it looks like `sensor_frame` is using `//pose/@degrees`, so I think it should be 1.9
</blockquote></details>

Ah, right. I've updated it to 1.9 in https://github.com/ignitionrobotics/sdformat/pull/659/commits/e7dc8be3e1ec2b89a7d6564deeccc1129c45d0e0


<!-- Sent from Reviewable.io -->

2021-09-16 16:13 UTC, azeey commented
___
*[src/parser.cc, line 237 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZy92J5D3fx06jt-S-:-MjjNPLP1mIL_FXv8Nf7:bvjdd9u) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L237)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

That's a good point. I'm not sure how we can avoid that unless we also reserve all names that start with double underscore. Alternatively, we can modify the poses of each element and not use a frame. 
</blockquote></details>

How about if I change the pattern to `proxy__<model name>__model__`?


<!-- Sent from Reviewable.io -->

2021-09-16 18:36 UTC, jennuine reviewed
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 7 of 21 files reviewed, 6 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[include/sdf/InterfaceElements.hh, line 51 at r8](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MjjaQPC1ik_HjQ19_Nv:-MjjaQPC1ik_HjQ19_Nw:bbmoewb) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/5c6bec203f729dbbc134c267d57c8654a9d376be/include/sdf/InterfaceElements.hh#L51)):*
> ```Hack
>   // deprecation warnings on memeber variables when simply instantiating this
>   // class.
>   // TODO(anyone) Remove the constructor and destructor once the depreceted
> ```

nit: depreceted -> deprecated
___
*[src/InterfaceElements_TEST.cc, line 2 at r8](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MjjjD3m9iCwpIs_lYpw:-MjjjD3m9iCwpIs_lYpx:bbdmuj) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/5c6bec203f729dbbc134c267d57c8654a9d376be/src/InterfaceElements_TEST.cc#L2)):*
> ```cpp
> /*
>  * Copyright (C) 2018 Open Source Robotics Foundation
> ```

nit: 2018 -> 2021
___
*[src/parser.cc, line 237 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZy92J5D3fx06jt-S-:-MjjrAw03D2OK8JRh1ON:b-ie6ydo) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L237)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

How about if I change the pattern to `proxy__<model name>__model__`?
</blockquote></details>

or `merged__<model name>__model__`?


<!-- Sent from Reviewable.io -->

2021-09-20 22:18 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 7 of 21 files reviewed, 4 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[include/sdf/InterfaceElements.hh, line 51 at r8](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MjjaQPC1ik_HjQ19_Nv:-Mk4HE9M7607bNkOAL34:buxq6kl) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/5c6bec203f729dbbc134c267d57c8654a9d376be/include/sdf/InterfaceElements.hh#L51)):*
<details><summary><i>Previously, jennuine (Jenn Nguyen) wrote…</i></summary><blockquote>

nit: depreceted -> deprecated
</blockquote></details>

Done. https://github.com/ignitionrobotics/sdformat/pull/659/commits/de373d05daec3aff6b9ac2874c240c4ad53e7896
___
*[src/InterfaceElements_TEST.cc, line 2 at r8](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MjjjD3m9iCwpIs_lYpw:-Mk4HFAw10eFc3P46ZxD:buxq6kl) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/5c6bec203f729dbbc134c267d57c8654a9d376be/src/InterfaceElements_TEST.cc#L2)):*
<details><summary><i>Previously, jennuine (Jenn Nguyen) wrote…</i></summary><blockquote>

nit: 2018 -> 2021
</blockquote></details>

Done. https://github.com/ignitionrobotics/sdformat/pull/659/commits/de373d05daec3aff6b9ac2874c240c4ad53e7896
___
*[src/parser.cc, line 237 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZy92J5D3fx06jt-S-:-Mk4HG_90qnvBfqdmzdG:b-5zr13i) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L237)):*
<details><summary><i>Previously, jennuine (Jenn Nguyen) wrote…</i></summary><blockquote>

or `merged__<model name>__model__`?
</blockquote></details>

Ok, changed to `merged__<model name>__model__` in  https://github.com/ignitionrobotics/sdformat/pull/659/commits/de373d05daec3aff6b9ac2874c240c4ad53e7896


<!-- Sent from Reviewable.io -->

2021-09-20 22:51 UTC, scpeters reviewed
> Reviewed 2 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: 9 of 21 files reviewed, 1 unresolved discussion (waiting on @azeey and @EricCousineau-TRI)

___
*[src/parser.cc, line 237 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-MiZy92J5D3fx06jt-S-:-Mk4Nu_39lJW9EdSGzIc:b32w0x) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/src/parser.cc#L237)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Ok, changed to `merged__<model name>__model__` in  https://github.com/ignitionrobotics/sdformat/pull/659/commits/de373d05daec3aff6b9ac2874c240c4ad53e7896
</blockquote></details>

OK
___
*[test/integration/model/merge_robot/model.sdf, line 275 at r3](https://reviewable.io/reviews/ignitionrobotics/sdformat/659#-Mi_0OtNBT9c7vI0-hb-:-Mk4OxpU683tDq3brFy0:b32w0x) ([raw file](https://github.com/ignitionrobotics/sdformat/blob/64413f3ec1619b1af559f426b34a1c4c742ca073/test/integration/model/merge_robot/model.sdf#L275)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done. Added more tests in https://github.com/ignitionrobotics/sdformat/pull/659/commits/923cc729451f4aa98b801ac7fec54323d726d5b6. Instead creating a new joint, I modified the existing one. Let me know if that's okay.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-09-20 23:03 UTC, scpeters approved these changes
> Reviewed 5 of 11 files at r6, 1 of 2 files at r7, 3 of 3 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdformat/659)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2021-09-20 23:18 UTC, merged