Added ToElement conversion for Collision, Surface, and Visual
ignitionrobotics/sdformat pull request #777
Opened 2021-12-08 17:09 UTC by nkoenig

Signed-off-by: Nate Koenig <nate@openrobotics.org>

# 🎉 New feature

## Summary

Add `ToElement` conversion function for `Collision`, `Contact`, `Surface`, and `Visual`. There are a lot of fields for Surface and Contact that are currently not parsed, I'm leaving this as future work.

## Test it

Run the tests.

## Checklist
- [X] Signed all commits for DCO
- [X] Added tests
- [X] Updated documentation (as needed)
- [X] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [X] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-12-09 09:41 UTC, ahcorde requested changes

2021-12-09 09:41 UTC, ahcorde commented on src/Visual_TEST.cc
> +  visual.SetTransparency(0.2);
```suggestion
  visual.SetTransparency(0.2f);
```
https://build.osrfoundation.org/job/sdformat-ci-pr_any-windows7-amd64/2782/msbuild/new/

2021-12-09 19:38 UTC, iche033 approved these changes

2021-12-09 20:08 UTC, merged

2022-04-13 21:30 UTC, osrf-triage commented
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-04-13-fortress-edifice/1367/1