Added Friction and ODE classes
ignitionrobotics/sdformat pull request #955
Opened 2022-04-07 20:05 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🎉 New feature

related with this issue https://github.com/ignitionrobotics/sdformat/issues/954

## Summary

Added Friction and ODE classes

## Test it

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-04-08 04:24 UTC, scpeters commented
@azeey this might be the right time to try to clean up our friction parameters, per https://github.com/ignitionrobotics/sdformat/issues/31 and specifically this comment: https://github.com/ignitionrobotics/sdformat/issues/31#issuecomment-951137292

2022-04-08 15:13 UTC, azeey commented
> @azeey this might be the right time to try to clean up our friction parameters, per #31 and specifically this comment: [#31 (comment)](https://github.com/ignitionrobotics/sdformat/issues/31#issuecomment-951137292)

I think @ahcorde is pressed for time and needs this for the USD-SDF work. But yeah, we might be able to make time for it in the next couple months.

2022-04-08 16:14 UTC, scpeters commented
> > @azeey this might be the right time to try to clean up our friction parameters, per #31 and specifically this comment: [#31 (comment)](https://github.com/ignitionrobotics/sdformat/issues/31#issuecomment-951137292)
> 
> I think @ahcorde is pressed for time and needs this for the USD-SDF work. But yeah, we might be able to make time for it in the next couple months.

oh I didn't look at the labels and thought this was for deepmind. Since it is creating an API, I'd like to think a little extra about its design

2022-04-08 16:23 UTC, scpeters commented
> oh I didn't look at the labels and thought this was for mujoco. Since this PR is creating an API, I'd like to think a little extra about its design

my main concern is that the fact that all friction parameters are in the `<ode>` block feels like a hack. We started trying to clean this up with the [FrictionPyramid](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/physics/SurfaceParams.hh#L34-L161) class in gazebo classic but never pushed that model structure into SDFormat.

so, do we want to encode the hacky SDFormat structure in our C++ API in libsdformat12 and then deprecate it in libsdformat13? The advantage of that would be that we could get it merged faster, and that it maintains a transparent mapping between the DOM API and the SDFormat data structure. Or do we want to try for a better API now?

2022-04-09 00:02 UTC, scpeters commented
> > oh I didn't look at the labels and thought this was for mujoco. Since this PR is creating an API, I'd like to think a little extra about its design
> 
> my main concern is that the fact that all friction parameters are in the `<ode>` block feels like a hack. We started trying to clean this up with the [FrictionPyramid](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/physics/SurfaceParams.hh#L34-L161) class in gazebo classic but never pushed that model structure into SDFormat.
> 
> so, do we want to encode the hacky SDFormat structure in our C++ API in libsdformat12 and then deprecate it in libsdformat13? The advantage of that would be that we could get it merged faster, and that it maintains a transparent mapping between the DOM API and the SDFormat data structure. Or do we want to try for a better API now?

after discussing offline, it sounds reasonable to proceed with this approach for `libsdformat12` since it matches the specification and deprecate it in `libsdformat13` if we change how the friction parameters are specified per #31

2022-04-13 16:10 UTC, azeey requested changes

2022-04-13 16:10 UTC, azeey commented on include/sdf/Surface.hh
> +    public: void SetFdir1(ignition::math::Vector3d _fdir);
The parameter should be a const ref.

2022-04-13 16:10 UTC, azeey commented on src/Surface.cc
> +  // Check that the provided SDF element is a <contact>
`<contact>` -> `<friction>`.

2022-04-13 16:10 UTC, azeey commented on src/Surface.cc
> +  // \todo(nkoenig) Parse the remaining collide properties.
Is this TODO needed? If so, can you update it?

2022-04-13 16:10 UTC, azeey commented on src/Surface_TEST.cc
> +TEST(DOMfriction, DefaultConstruction)
Since the test is named `DefaultConstruction`, I think it should test the default values, not ones set using the `Set*` functions.

2022-04-13 16:10 UTC, azeey commented on src/Surface_TEST.cc
> +  sdf::ODE ode;
Since the test is named `DefaultConstruction`, I think it should test the default values, not ones set using the `Set*` functions.

2022-04-13 20:23 UTC, azeey approved these changes

2022-04-13 20:23 UTC, azeey commented on src/Surface.cc
> +  // \todo(nkoenig) Parse the remaining collide properties.
Can you update the username?

2022-04-14 06:45 UTC, merged