Added <shininess> to <material>
ignitionrobotics/sdformat pull request #985
Opened 2022-04-18 17:20 UTC by WilliamLewww

# 🎉 Added ```<shininess>``` to ```<material>```

## Summary
When using default shaders in gazebo, the ogre's default shininess is 0 causing the specular components to have no effect. Without having a shininess element, we are unable to utilize specular highlights with default shaders.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-04-18 17:32 UTC, ahcorde requested changes
CI  

```
/github/workspace/include/sdf/Material.hh:119:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
```

2022-04-21 16:50 UTC, ahcorde approved these changes

2022-04-21 18:27 UTC, iche033 reviewed
how about also updating the `Load` function to load `shininess` value from SDF?

2022-04-21 20:47 UTC, iche033 approved these changes

2022-04-22 08:16 UTC, merged